export const sampleData = {
  adult: false,
  backdrop_path: '/poNxNrYGP4r62KoXCGg1fcfquNJ.jpg',
  belongs_to_collection: null,
  budget: 0,
  genres: ['Drama', 'Comedy', 'Romance'],
  homepage: 'http://babyteeth.movie',
  id: 522098,
  imdb_id: 'tt8399664',
  original_language: 'en',
  original_title: 'Babyteeth',
  overview:
    'A terminally ill teen upsets her parents when she falls in love with a small-time drug dealer.',
  popularity: 11.035,
  poster_path: '/aINpljdt3VVMrCLtJW4BektwYOp.jpg',
  release_date: '2020-06-19',
  revenue: 989310,
  runtime: 118,
  spoken_languages: ['English'],
  status: 'Released',
  tagline: '',
  title: 'Babyteeth',
  video: false,
  vote_average: 6.9,
  vote_count: 218,
}
